sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
os:
  - linux
before_script:
  - npm ci
  - npm run build
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
