sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 6
  - 7
os:
  - linux
before_script:
  - yarn install
  - yarn link || true
  - npm run lint
  - npm run build
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
