sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
os:
  - linux
before_script:
  - npm install
  - npm run lint
  - npm run build
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
